### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by sjmills** [StjerneIdioten/I3D-Blender-Addon#156]
I downloaded the latest version (4.1.1) and the latest Blender (3.3.0 on Mac) and I get this error when trying to install the plugin zip (the pasted text was acquired by taking a screenshot of the error, which is not selectable in Blender (WTH?!), then opening it in Preview on Mac, which recognizes the text - hopefully it got it all correct). I was previously using build 1.2.0 with Blender 3.2 (not 100% sure on the Blender version):

Traceback (most recent call last):
File "/Users/tut/Library/Application Support/Blender/3.3/scripts/addons/i3dio/_init.py", line 48, in register
import Ixml
ModuleNotFoundError: No module named 'Ixml'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/Applications/Blender.app/Contents/Resources/3.3/scripts/modules/addon utils.py", line 369, in enable
mod.register()
File "/Users/tut/Library/Application Support/Blender/3.3/scripts/addons/i3dio/_init_py", line 52, in register
if ctypes.windll.shell32.IsUserAnAdmin(:
AttributeError: module 'types' has no attribute 'windll'

**Comment by StjerneIdioten** [comment]
Unfortunately the addon assumes that you are running on a Windows platform. I know that Blender is cross-platform, but Giants Engine (which this addon targets) is only running on Windows and therefore I did not try and make it cross platform. I could technically do the check for admin rights (Which is what fails, since it's windows specific currently) in a way where OSX would also be supported. But I have no way of checking if it works on OSX and I can also not guarantee that the other parts of the code is working on anything but Windows 🤷‍♂️

**Comment by bash0** [comment]
The same issue exists on Linux. Installation fails with a reference to windll. Would be great if this could be made platform-independent.

**Comment by StjerneIdioten** [comment]
> The same issue exists on Linux. Installation fails with a reference to windll. Would be great if this could be made platform-independent.

It was made under the assumption that people would be modding on Windows, since that's the only place where the Giants Engine runs as far as I know 😉 But of course there might be situations where people want to do the actual modeling on another platform, but so far this is the first complaint I've heard about it. 

If anybody wants to change it to be platform independent I will happily accept a pull request, but unfortunately at the moment I am too busy to fix it myself.

**Comment by CCL1106** [comment]
Hey, 
i would also enjoy to use the exporter on macOS, but its not that important for me. I can´t tell anything about linux, but Giants engine is working fine on macOS (even with M1) since FS22.
So, FYI, keep dooing more important stuff

**Comment by StjerneIdioten** [comment]
> Hey, i would also enjoy to use the exporter on macOS, but its not that important for me. I can´t tell anything about linux, but Giants engine is working fine on macOS (even with M1) since FS22. So, FYI, keep dooing more important stuff

I would assume that you are running GE through some form of compatibility layer then, like Wine?

**Comment by StjerneIdioten** [comment]
@NMC-TBone with the removal of the LXML installation and conversion of just about everything to use Pathlib wouldn't we technically be Linux/MacOS compatible now if anyone was so inclined for some reason? 😅

**Comment by NMC-TBone** [comment]
> [@NMC-TBone](https://github.com/NMC-TBone) with the removal of the LXML installation and conversion of just about everything to use Pathlib wouldn't we technically be Linux/MacOS compatible now if anyone was so inclined for some reason? 😅

From the addons point of view, I guess the answer is yes.
But if they want to get the raw .i3d file to a .shapes file they would still need to use either the i3dconverter.exe or GE and as far as I know those only work on windows

**Comment by StjerneIdioten** [comment]
> From the addons point of view, I guess the answer is yes. But if they want to get the raw .i3d file to a .shapes file they would still need to use either the i3dconverter.exe or GE and as far as I know those only work on windows

Kind of, there is only an .exe file available, but if one really wanted to you could setup a shortcut that runs it through Wine and give that to addon as the converter to run. As it currently stands we don't have anything setup to test on those other platforms so we might introduce something later, but I will try and keep in mind to not break support on other platforms deliberately 😅

**Comment by StjerneIdioten** [comment]
I will close this for now and if we ever break compatibility again, we can reopen it.
