### ISSUE TITLE
Plugin doesn't work in Blender 2.83.2

### ISSUE THREAD

**Issue by crisan211** [StjerneIdioten/I3D-Blender-Addon#46]
**Describe the bug**
The plugin doesn't work in Blender 2.83.2

**Log file**
Please generate a logfile by checking `'Output logfile'` in the exporter and attach it to the issue.
i3dio:<module>:INFO: Initialized logging for i3dio addon
Traceback (most recent call last):
  File "C:\Program Files (x86)\Blender\blender-2.83.2-windows64\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Program Files (x86)\Blender\blender-2.83.2-windows64\2.83\scripts\addons\i3dio\__init__.py", line 23, in <module>
    from . import (
  File "C:\Program Files (x86)\Blender\blender-2.83.2-windows64\2.83\scripts\addons\i3dio\ui_export.py", line 16, in <module>
    from . import (
  File "C:\Program Files (x86)\Blender\blender-2.83.2-windows64\2.83\scripts\addons\i3dio\exporter.py", line 18, in <module>
    from .i3d import I3D
  File "C:\Program Files (x86)\Blender\blender-2.83.2-windows64\2.83\scripts\addons\i3dio\i3d.py", line 213, in <module>
    from i3dio.node_classes.skinned_mesh import *
ModuleNotFoundError: No module named 'i3dio.node_classes.skinned_mesh'

**Screenshots**

**Comment by StjerneIdioten** [comment]
Some code from a new feature accidentally snuck its way into the develop branch, when doing a fix for some other stuff. Try again with the newest release and see if it doesn't load now.

**Comment by crisan211** [comment]
Now is working, thank you

**Comment by StjerneIdioten** [comment]
You are welcome, please continue reporting bugs/features you want :-)
